### ISSUE TITLE
Checking in...

### ISSUE THREAD

**Issue by marcoscaceres** [mikewest/lang-client-hint#5]
Hi, 
Just checking in to see how things are going with this incubation? Still happening? @mikewest?

**Comment by mikewest** [comment]
Conversation with folks internally at Google about `accept-language` and how wonderful and lovely it is. I, at least, am still interested in doing something in this space. Some other folks are less interested in dropping the functionality which `accept-language` enables.

TL;DR: Still incubatin'.

**Comment by marcoscaceres** [comment]
Thanks @mikewest! Will check in again in a few months.
